Apply minor fixes to opera CLI commands
xlab-si/xopera-opera pull request #109
Opened 2020-10-08 13:42 UTC by anzoman

Here we apply some changes for opera CLI commands, which are important
for better performance for the users and more readable code for the
developers. The fixes and improvements we are talking about are:

- fix imports within the code (ordering, unused imports)
- opera validate can now be used also with compressed CSARs
- use opera info state in deploy and undeploy commands
- add opera undeploy --resume/-r and --force/-f flags
- add opera init --clean/-c flag that solves the problem spotted in #105
- add integration test for all opera commands

2020-10-15 17:03 UTC, sstanovnik requested changes
These changes all seem sensible. But it's all in one commit, which is bad because there are _sooo_ many different things you've changed. And it's not just "minor fixes to commands", you have new functionality in there, along with new tests and formatting changes. I suggest splitting into:

* tests

2020-10-15 17:03 UTC, sstanovnik commented on tests/integration/cli_commands/runme.sh
> +# deploy service template, but interrupt after 0.5 seconds
after 1 second, right? :)

2020-10-16 11:19 UTC, anzoman commented on src/opera/commands/init.py
> +
Done

2020-10-16 11:19 UTC, anzoman commented on tests/integration/cli_commands/runme.sh
> +# deploy service template, but interrupt after 0.5 seconds
Yass

2020-10-16 11:38 UTC, anzoman commented
@sstanovnik thanks for your comments. I have made some changes. And I agree that one commit is not enough so we have 7 commits now.

2020-10-30 10:02 UTC, matejart reviewed
I can offer no comment at this time.

2020-12-08 08:30 UTC, sstanovnik approved these changes

2020-12-08 08:30 UTC, merged