Make TOSCA properties required by default
xlab-si/xopera-opera pull request #132
Opened 2020-12-07 10:23 UTC by anzoman

Here we are addressing the issue that has been originally spotted in
#131. There is an additional requirement for property (and parameter
definitions) that has to be satisfied in order to stick with the
TOSCA Simple Profile in YAML version 1.3. Every defined property
should be considered required by default unless its required keyname is
explicitly set to false. With these changes we make sure that the users
will be warned if some required property is missing its value and in
these cases the deployment process will fail. According to that we also
needed to update some of TOSCA templates among the examples and
integration tests as there were required properties that were not used.

Fixes #131.

2020-12-08 10:14 UTC, sstanovnik requested changes
This looks good, but can you add a simple integration test that expects an error when you don't specify a required property?

2020-12-09 08:36 UTC, anzoman commented
@sstanovnik merci beaucoup for going through this PR. I think that we don't need an integration tests for that as this can be tested more easily so I have just added some simple unit tests.

2020-12-15 11:03 UTC, sstanovnik approved these changes

2020-12-15 11:03 UTC, sstanovnik commented
lgtm!

2020-12-15 11:03 UTC, merged