CLI updates: help messages, resolving issues, tab completion update etc.
xlab-si/xopera-opera pull request #175
Opened 2021-02-02 13:23 UTC by anzoman

This PR applies some CLI updates:

- tab completion for `opera diff` and `opera update`
- save results from `opera outputs` and `opera info` to a file
- update help messages for CLI commands
- add host requirement to `noimpl` node from integration tests
- remove the duplicated archive check in `opera unpackage` command

Fixes #145, #151.

2021-02-09 09:02 UTC, sstanovnik requested changes
Just two small comments.

2021-02-09 10:22 UTC, anzoman commented on src/opera/commands/unpackage.py
> +def unpackage(csar_input: str, output_dir: str):
Sure we can, I can put the commit with this change in a separate draft PR and specify that it should be merged before releasing version `0.6.5`. Would that be okay?

2021-02-09 10:26 UTC, anzoman commented on tests/integration/misc_tosca_types/modules/node_types/noimpl/noimpl.yaml
> +          relationship: tosca.relationships.HostedOn
It should but the problem is in `opera`'s parser which does not yet recognize these type of requirement errors and we will need some time to fix this and the `opera validate` will be able to catch problems like this one.

2021-02-09 10:26 UTC, anzoman commented
@sstanovnik many thanks for your review, I've answered your comments.

2021-02-09 11:51 UTC, sstanovnik commented on src/opera/commands/unpackage.py
> +def unpackage(csar_input: str, output_dir: str):
That would be absolutely perfect!

2021-02-09 11:51 UTC, sstanovnik commented on tests/integration/misc_tosca_types/modules/node_types/noimpl/noimpl.yaml
> +          relationship: tosca.relationships.HostedOn
Okay!

2021-02-09 12:04 UTC, anzoman commented on src/opera/commands/unpackage.py
> +def unpackage(csar_input: str, output_dir: str):
Great, I've created a draft PR here: #179.

2021-02-09 12:06 UTC, anzoman commented
@sstanovnik removing the duplicated archive check in `opera unpackage` command has been moved to #179 as you requested and will be merged right before we release version `0.6.5`.

2021-02-12 07:56 UTC, sstanovnik approved these changes

2021-02-12 07:57 UTC, sstanovnik commented
Thanks!

2021-02-12 07:57 UTC, merged