Fix opera storage path when deploying compressed CSAR
xlab-si/xopera-opera pull request #96
Opened 2020-09-02 11:28 UTC by anzoman

There was an idea to introduce the deployment the compressed TOSCA
CSAR. In #82 we made sure that initialized CSARs are deployed from
their extracted root which is usually in .opera/csars/csar (other
storage locations can be used instead of .opera by using
--instance-path CLI flag). That's why we forced opera to move to
the extracted csars storage dir before the deployment. However, we
have forgotten one tiny detail - storage instance files. These are
stored in .opera/instances and accessed during the execution. To
prevent the creation of these files in csars/csar subfolder we
ensured that opera goes two levels up in the storage folder structure.
_______________________

The zipped CSAR this can be tested with is here: [test.zip](https://github.com/xlab-si/xopera-opera/files/5161955/test.zip)

2020-09-30 17:44 UTC, sstanovnik requested changes
This looks sensible. I would just add another integration test to make sure we don't break this in the future:

* zip files into a csar
* move the zip into another dir
* init opera with the csar in that dir
* run deplyoment, make sure it's successful
* make sure there's exactly one .opera/ folder

2020-09-30 17:44 UTC, sstanovnik commented on src/opera/commands/deploy.py
> +        # go away chdir(csar_dir)
Make this comment go away :)

2020-09-30 17:44 UTC, sstanovnik commented on src/opera/commands/undeploy.py
> +        # go away chdir(csar_dir)
Commnet awae.

2020-09-30 17:44 UTC, sstanovnik commented on src/opera/instance/node.py
> +        self.run_operation("HOST", "Standard", "create", verbose, workdir,)
This has an extra comma.

2020-09-30 17:44 UTC, sstanovnik commented on src/opera/instance/node.py
> +        self.run_operation("HOST", "Standard", "configure", verbose, workdir,)
Extra comma.

2020-09-30 17:44 UTC, sstanovnik commented on src/opera/instance/node.py
> +                    workdir,
Extra comma.

2020-09-30 17:44 UTC, sstanovnik commented on src/opera/instance/node.py
> +                    workdir,
Co mm a.

2020-09-30 17:44 UTC, sstanovnik commented on src/opera/instance/node.py
> +                    workdir,
co-ma

2020-09-30 17:44 UTC, sstanovnik commented on src/opera/instance/node.py
> +                    workdir,
co. ma.

2020-09-30 17:44 UTC, sstanovnik commented on src/opera/instance/node.py
> +        self.run_operation("HOST", "Standard", "start", verbose, workdir,)
koh. mah.

2020-09-30 17:44 UTC, sstanovnik commented on src/opera/instance/node.py
> +        self.run_operation("HOST", "Standard", "stop", verbose, workdir,)
koh-mah.

2020-09-30 17:44 UTC, sstanovnik commented on src/opera/instance/node.py
> +        self.run_operation("HOST", "Standard", "delete", verbose, workdir,)
comma.

2020-09-30 17:44 UTC, sstanovnik commented on src/opera/template/node.py
> +            return operation.run(host, instance, verbose, workdir,)
comma

2020-09-30 17:44 UTC, sstanovnik commented on src/opera/template/operation.py
> +            workdir,
com

2020-09-30 17:44 UTC, sstanovnik commented on src/opera/template/relationship.py
> +            return operation.run(host, instance, verbose, workdir,)
come-ah

2020-10-02 11:41 UTC, anzoman commented on src/opera/commands/deploy.py
> +        # go away chdir(csar_dir)
Yes :).

2020-10-02 11:41 UTC, anzoman commented on src/opera/commands/undeploy.py
> +        # go away chdir(csar_dir)
Yiz.

2020-10-02 11:41 UTC, anzoman commented on src/opera/instance/node.py
> +                    workdir,
Fixed.

2020-10-02 11:42 UTC, anzoman commented on src/opera/instance/node.py
> +        self.run_operation("HOST", "Standard", "create", verbose, workdir,)
The comma was removed.

2020-10-02 11:42 UTC, anzoman commented on src/opera/instance/node.py
> +        self.run_operation("HOST", "Standard", "configure", verbose, workdir,)
Removed.

2020-10-02 11:42 UTC, anzoman commented on src/opera/instance/node.py
> +                    workdir,
Re mo ved.

2020-10-02 11:42 UTC, anzoman commented on src/opera/instance/node.py
> +                    workdir,
Re-moved.

2020-10-02 11:42 UTC, anzoman commented on src/opera/instance/node.py
> +                    workdir,
Re. moved.

2020-10-02 11:42 UTC, anzoman commented on src/opera/instance/node.py
> +        self.run_operation("HOST", "Standard", "stop", verbose, workdir,)
Reh-moved.

2020-10-02 11:43 UTC, anzoman commented on src/opera/instance/node.py
> +        self.run_operation("HOST", "Standard", "delete", verbose, workdir,)
This was refactored.

2020-10-02 11:43 UTC, anzoman commented on src/opera/instance/node.py
> +        self.run_operation("HOST", "Standard", "start", verbose, workdir,)
Reh. moved.

2020-10-02 11:44 UTC, anzoman commented on src/opera/template/node.py
> +            return operation.run(host, instance, verbose, workdir,)
not anymore

2020-10-02 11:45 UTC, anzoman commented on src/opera/template/relationship.py
> +            return operation.run(host, instance, verbose, workdir,)
Removed.

2020-10-02 11:45 UTC, anzoman commented on src/opera/template/operation.py
> +            workdir,
rem.

2020-10-02 11:47 UTC, anzoman commented
@sstanovnik now I have resolved your comments and have improved the CSAR integration test as you requested.

2020-10-02 17:37 UTC, sstanovnik approved these changes
Great!

2020-10-02 17:38 UTC, merged